#!/bin/bash

ln -f ~/dots/gitconfig ~/.gitconfig
ln -f ~/dots/githelpers ~/.githelpers
ln -f ~/dots/tmux.conf ~/.tmux.conf
ln -f ~/dots/vimrc ~/.vimrc
ln -f ~/dots/zshrc ~/.zshrc
ln -f ~/dots/zshrc ~/.zshrc
mkdir -p ~/.config/nvim 
ln -f ~/dots/config/nvim/init.vim  ~/.config/nvim/init.vim
