require("everything.lazy-bootstrap")
require("everything.leader")
require("everything.lazy")
require("everything.remap")
require("everything.options")
require("everything.colors")
require("everything.lsp")
