gui:
  showIcons: true
git:
  autoFetch: false
  autoRefresh: false
  paging:
    colorArg: always
    useConfig: false
    pager: delta --paging=never --line-numbers
update:
  method: prompt
  days: 1
